# Generated by Django 4.2.7 on 2023-11-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('narxi', models.CharField(max_length=30)),
                ('yaroq_sana', models.DateTimeField()),
                ('img', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
